### ISSUE TITLE
Specify what Document ID is in README.md

### ISSUE THREAD

**Issue by cailborg** [matthieubellon/kribble#1]
This is not really an issue, but being new to Figma, it took me ages to work out which part of the share link would actually work and not throw errors (i tried just pasting the whole link, and then various parts of the link before i worked it out)

Just somewhere in the readme specifying how to find the Document ID might be helpful.

This project is awesome though!

**Comment by matthieubellon** [comment]
Sorry for the waste of time, UI was clearly misleading. Fixed by adding the info directly near the input. Thanks for reporting & feedback !
